site_name: OfficialEye
site_url: https://officialeye.zerobone.net/
site_author: Alexander Mayorov
docs_dir: docs
repo_name: ZeroBone/OfficialEye
repo_url: https://github.com/ZeroBone/OfficialEye
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    logo: material/file-eye
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.path
    - search.share
    - search.suggest
    - search.highlight
    - content.tooltips
    - toc.follow
    - navigation.instant
    - navigation.instant.prefetch
  language: en
  palette:
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - privacy:
      enabled: !ENV [CI, false]
  - gen-files:
      scripts:
        - docs_dynamic/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZeroBone/OfficialEye
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Usage:
      - Introduction: index.md
      - usage/examples.md
      - "Getting Started":
          - usage/getting-started/index.md
          - usage/getting-started/yaml-basics.md
          - usage/getting-started/architecture.md
      - Scripting:
          - usage/scripting/overview.md
          - usage/scripting/matching-engines.md
          - usage/scripting/supervision-engines.md
          - usage/scripting/mutators.md
          - usage/scripting/feature-classes.md
          - usage/scripting/interpretation-methods.md
      - Other:
          - License: usage/other/license.md
  - Development:
      - dev/changelog.md
  - "API Reference": reference/

extra_css:
  - assets/stylesheets/style.css

copyright: |
  Copyright &copy; 2023-2024 <a href="https://github.com/ZeroBone" target="_blank" rel="noopener">Alexander Mayorov</a>
