[project]
name = "officialeye"
version = "1.0.3"
description = "Default template for PDM package"
authors = [
    {name = "Alexander Mayorov", email = "zb@zerobone.net"},
]
dependencies = [
    "click>=8.1.7",
    "numpy>=1.26.2",
    "opencv-contrib-python-headless",
    "pytesseract",
    "pyyaml",
    "strictyaml==1.7.3",
    "z3-solver",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}


[project.scripts]
officialeye = "officialeye.officialeye:cli"
[tool.pdm]
package-type = "application"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.scripts]
docs-serve = "mkdocs serve"
docs-build = "mkdocs build"

[tool.pdm.dev-dependencies]
doc = [
    "mkdocs-material",
    "mkdocs-material[imaging]",
    "mkdocs-minify-plugin",
    "mkdocstrings",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mkdocs-literate-nav"
]
test = [
    "pytest"
]